// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {ThemeProvider} from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next pages",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={"min-h-dvh"}>
        <head>
            <title>Localbooru</title>
            <meta name={"description"} content={"The local booru"} />
        </head>
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh`}
      >
      <ThemeProvider attribute={"class"} defaultTheme={"system"} enableSystem={false}>
        {children}
      </ThemeProvider>
      </body>


      </html>
  );
}
